import { randomUUID } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { HypervCimInventoryAdapter } from '../hyperv/cim-inventory.js'
import { toHypervCollectionPayload, toHypervInventoryEnvelope, toHypervTelemetryEnvelope } from '../hyperv/canonical-envelope.js'
import { normalizeHypervPerformanceOutput } from '../hyperv/performance.js'
import { ScvmmInventoryAdapter } from '../scvmm/inventory.js'
import { ConstrainedPowerShellRunner } from '../security/powershell-runner.js'
import { EncryptedWindowsSpool, WindowsSpoolUploader } from './encrypted-spool.js'
import { statePaths, type WindowsCollectorIdentity } from './enrollment.js'
import { WindowsBundleSigner } from './signed-bundle.js'

export interface WindowsCollectorConfig { stateDirectory: string; spoolDirectory: string; scriptsDirectory: string; manifestPath: string; managementPlaneUid: string; mode: 'SCVMM' | 'LOCAL_HYPERV'; scvmm?: { server: string; port: number }; upload?: { endpoint: string; allowedHosts: string[]; privateAddressAllowedHosts?: string[] }; intervalSeconds: number; maxSpoolBytes: number; maxSpoolItems: number; offlineExportDirectory?: string }
export async function loadWindowsCollectorConfig(path: string): Promise<WindowsCollectorConfig> { const value = JSON.parse(await readFile(path, 'utf8')) as WindowsCollectorConfig; if (!['SCVMM', 'LOCAL_HYPERV'].includes(value.mode) || !Number.isSafeInteger(value.intervalSeconds) || value.intervalSeconds < 60) throw new Error('Collector mode or interval is invalid'); if (value.mode === 'SCVMM' && !value.scvmm) throw new Error('SCVMM configuration is required'); if (!value.upload && !value.offlineExportDirectory) throw new Error('Upload or offline export must be configured'); return value }

export class WindowsCollectorRuntime {
  constructor(private readonly config: WindowsCollectorConfig, private readonly runner: ConstrainedPowerShellRunner, private readonly spool: EncryptedWindowsSpool, private readonly signer: WindowsBundleSigner, private readonly identity: WindowsCollectorIdentity, private readonly uploader?: WindowsSpoolUploader) {}
  async collectOnce(now = new Date()) { const collectionRunId = randomUUID(); const context = { connectorVersion: process.env.COLLECTOR_VERSION ?? '0.1.0', collectionRunId, collectedAt: now.toISOString() }; const inventory = this.config.mode === 'SCVMM' ? await new ScvmmInventoryAdapter(this.runner).collect(this.config.scvmm!, context) : await new HypervCimInventoryAdapter(this.runner).collect(context); const performance = normalizeHypervPerformanceOutput(await this.runner.runLocalHypervPerformance()); const inventoryEnvelope = toHypervInventoryEnvelope(this.identity.integrationId, this.config.managementPlaneUid, inventory); const telemetryEnvelope = toHypervTelemetryEnvelope(this.identity.integrationId, this.config.managementPlaneUid, now.toISOString(), performance.facts, performance.gaps); const bundle = this.signer.create(collectionRunId, toHypervCollectionPayload(inventoryEnvelope, telemetryEnvelope), now); await this.spool.enqueue(bundle.bundleId, bundle.schemaVersion, Buffer.from(JSON.stringify(bundle))); return { collectionRunId, bundleId: bundle.bundleId } }
  async flush() { if (this.uploader) return this.uploader.flushOnce(); if (!this.config.offlineExportDirectory) return { sent: 0 }; await mkdir(this.config.offlineExportDirectory, { recursive: true }); let sent = 0; for (const item of await this.spool.list()) { if (!this.spool.accepts(item.schemaVersion)) continue; await writeFile(join(this.config.offlineExportDirectory, `${item.queueId}.${item.bundleId}.bundle`), item.payload, { flag: 'wx', mode: 0o600 }); await this.spool.remove(item.queueId); sent++ } return { sent } }
  async run(signal?: AbortSignal) { await this.runner.initialize(); do { await this.collectOnce(); await this.flush(); if (signal?.aborted) break; await new Promise((resolve) => setTimeout(resolve, this.config.intervalSeconds * 1000)) } while (!signal?.aborted) }
}

export async function createWindowsCollectorRuntime(config: WindowsCollectorConfig) { const paths = statePaths(config.stateDirectory); const identity = JSON.parse(await readFile(paths.identity, 'utf8')) as WindowsCollectorIdentity; const runner = new ConstrainedPowerShellRunner({ scriptsDirectory: config.scriptsDirectory, manifestPath: config.manifestPath, allowedScvmmEndpoints: config.scvmm ? [config.scvmm] : [] }); const spool = new EncryptedWindowsSpool({ directory: config.spoolDirectory, key: Buffer.from((await readFile(paths.spoolKey, 'utf8')).trim(), 'base64'), maxBytes: config.maxSpoolBytes, maxItems: config.maxSpoolItems, acceptedSchemaVersions: ['1.0'] }); const signer = new WindowsBundleSigner(await readFile(paths.privateKey, 'utf8'), { orgId: identity.orgId, collectorId: identity.collectorId, signatureKeyId: identity.keyId }); const uploader = config.upload ? new WindowsSpoolUploader(spool, { ...config.upload, bearerToken: (await readFile(paths.transportToken, 'utf8')).trim() }) : undefined; return new WindowsCollectorRuntime(config, runner, spool, signer, identity, uploader) }
