import { createCipheriv, createDecipheriv, randomBytes, randomUUID } from 'node:crypto'
import { lookup } from 'node:dns/promises'
import { mkdir, open, readFile, readdir, rename, stat, unlink } from 'node:fs/promises'
import { isIP } from 'node:net'
import { join } from 'node:path'
import { Agent, fetch as undiciFetch } from 'undici'
import { redactWindowsCollectorError } from '../security/redaction.js'

interface Item { queueId: string; bundleId: string; schemaVersion: string; createdAt: string; attempts: number; nextAttemptAt: string; payload: Buffer; lastError?: string }
const privateAddress = (address: string) => { const value = address.toLowerCase(); if (value === '::1' || value.startsWith('fc') || value.startsWith('fd') || /^fe[89ab]/.test(value) || value.startsWith('::ffff:')) return true; const parts = value.split('.').map(Number); return parts.length === 4 && (parts[0] === 10 || parts[0] === 127 || parts[0] === 0 || (parts[0] === 172 && parts[1]! >= 16 && parts[1]! <= 31) || (parts[0] === 192 && parts[1] === 168) || (parts[0] === 169 && parts[1] === 254)) }
const lookupPinned = (addresses: string[]) => (_hostname: string, options: any, callback: (...args: any[]) => void) => { const rows = addresses.map((address) => ({ address, family: isIP(address) })); options?.all ? callback(null, rows) : callback(null, rows[0]!.address, rows[0]!.family) }

export class EncryptedWindowsSpool {
  private tail: Promise<void> = Promise.resolve()
  constructor(private readonly config: { directory: string; key: Buffer; maxBytes: number; maxItems: number; acceptedSchemaVersions: string[] }) { if (config.key.length !== 32) throw new Error('Spool key must be 32 bytes'); if (!Number.isSafeInteger(config.maxBytes) || config.maxBytes <= 0 || !Number.isSafeInteger(config.maxItems) || config.maxItems <= 0) throw new Error('Positive spool bounds are required') }
  async initialize() { await mkdir(this.config.directory, { recursive: true }) }
  async enqueue(bundleId: string, schemaVersion: string, payload: Buffer) { return this.exclusive(async () => { await this.initialize(); const usage = await this.usage(); if (usage.items >= this.config.maxItems) throw new Error('COLLECTOR_SPOOL_BACKPRESSURE'); const now = new Date(); const item: Item = { queueId: `${now.valueOf().toString().padStart(13, '0')}-${randomUUID()}`, bundleId, schemaVersion, createdAt: now.toISOString(), attempts: 0, nextAttemptAt: now.toISOString(), payload }; const bytes = this.encrypt(item); if (usage.bytes + bytes.length + ((usage.items + 1) * 4096) > this.config.maxBytes) throw new Error('COLLECTOR_SPOOL_BACKPRESSURE'); await this.write(item.queueId, bytes); return item.queueId }) }
  async list() { await this.initialize(); const names = (await readdir(this.config.directory)).filter((name) => name.endsWith('.bundle')).sort(); return Promise.all(names.map(async (name) => this.decrypt(await readFile(join(this.config.directory, name))))) }
  async usage() { await this.initialize(); const names = (await readdir(this.config.directory)).filter((name) => name.endsWith('.bundle')); let bytes = 0; for (const name of names) bytes += (await stat(join(this.config.directory, name))).size; return { items: names.length, bytes } }
  accepts(version: string) { return this.config.acceptedSchemaVersions.includes(version) }
  async remove(queueId: string) { if (!/^[0-9]{13}-[0-9a-f-]{36}$/.test(queueId)) throw new Error('Invalid queue ID'); await unlink(join(this.config.directory, `${queueId}.bundle`)) }
  async update(item: Item) { await this.exclusive(() => this.write(item.queueId, this.encrypt(item))) }
  private encrypt(item: Item) { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', this.config.key, iv); const encrypted = Buffer.concat([cipher.update(JSON.stringify({ ...item, payload: item.payload.toString('base64') })), cipher.final()]); return Buffer.from(JSON.stringify({ v: 1, iv: iv.toString('base64'), tag: cipher.getAuthTag().toString('base64'), encrypted: encrypted.toString('base64') })) }
  private decrypt(bytes: Buffer): Item { const envelope = JSON.parse(bytes.toString()); if (envelope.v !== 1) throw new Error('Unsupported spool envelope'); const decipher = createDecipheriv('aes-256-gcm', this.config.key, Buffer.from(envelope.iv, 'base64')); decipher.setAuthTag(Buffer.from(envelope.tag, 'base64')); const value = JSON.parse(Buffer.concat([decipher.update(Buffer.from(envelope.encrypted, 'base64')), decipher.final()]).toString()); return { ...value, payload: Buffer.from(value.payload, 'base64') } }
  private async write(id: string, bytes: Buffer) { const target = join(this.config.directory, `${id}.bundle`); const temp = `${target}.${randomUUID()}.tmp`; const handle = await open(temp, 'wx', 0o600); try { await handle.writeFile(bytes); await handle.sync() } finally { await handle.close() }; await rename(temp, target) }
  private async exclusive<T>(fn: () => Promise<T>) { const previous = this.tail; let release!: () => void; this.tail = new Promise<void>((resolve) => { release = resolve }); await previous; try { return await fn() } finally { release() } }
}

export class WindowsSpoolUploader {
  private lastError: string | null = null; private lastSuccessAt: string | null = null
  constructor(private readonly spool: EncryptedWindowsSpool, private readonly config: { endpoint: string; allowedHosts: string[]; privateAddressAllowedHosts?: string[]; bearerToken: string }) {}
  async flushOnce(now = new Date()) { const url = new URL(this.config.endpoint); if (url.protocol !== 'https:' || url.username || url.password || !this.config.allowedHosts.map((x) => x.toLowerCase()).includes(url.hostname.toLowerCase())) throw new Error('Upload endpoint is not approved credential-free HTTPS'); const addresses = (await lookup(url.hostname, { all: true })).map((row) => row.address); if (!addresses.length || (addresses.some(privateAddress) && !(this.config.privateAddressAllowedHosts ?? []).map((x) => x.toLowerCase()).includes(url.hostname.toLowerCase()))) throw new Error('Upload endpoint resolved to a prohibited address'); const agent = new Agent({ connect: { lookup: lookupPinned(addresses) } }); let sent = 0; try { for (const item of await this.spool.list()) { if (!this.spool.accepts(item.schemaVersion) || new Date(item.nextAttemptAt) > now) continue; try { const response = await undiciFetch(url, { method: 'POST', dispatcher: agent, headers: { 'content-type': 'application/json', authorization: `Bearer ${this.config.bearerToken}`, 'x-bundle-id': item.bundleId, 'x-bundle-schema-version': item.schemaVersion }, body: item.payload }); if (!response.ok) throw new Error(`Upload returned HTTP ${response.status}`); await this.spool.remove(item.queueId); sent++; this.lastError = null; this.lastSuccessAt = now.toISOString() } catch (error) { item.attempts++; item.lastError = redactWindowsCollectorError(error); item.nextAttemptAt = new Date(now.valueOf() + Math.min(3_600_000, 1000 * 2 ** Math.min(item.attempts, 12))).toISOString(); await this.spool.update(item); this.lastError = item.lastError } } } finally { await agent.close() }; return { sent } }
  async health() { const items = await this.spool.list(); return { healthy: this.lastError === null && items.every((item) => this.spool.accepts(item.schemaVersion)), queue: await this.spool.usage(), incompatible: items.filter((item) => !this.spool.accepts(item.schemaVersion)).length, lastError: this.lastError, lastSuccessAt: this.lastSuccessAt } }
}
